sudo: false
language: php
cache:
  apt: true
  directories:
    - node_modules
env:
  global:
    - WP_TRAVISCI=travis:phpunit
matrix:
  include:
  - php: 7
    env: WP_TRAVISCI=travis:js
  - php: 5.6
  - php: 5.6
    env: WP_TRAVIS_OBJECT_CACHE=true
    services: memcached
  - php: hhvm
    sudo: required
    dist: trusty
    group: edge
    addons:
      apt:
        packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
  - php: 7.0
  - php: nightly
  allow_failures:
  - php: hhvm
  - php: nightly
before_install:
- git clone https://github.com/WordPress/twentysixteen.git src/wp-content/themes/twentysixteen
- |
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
      mysql -u root -e "CREATE DATABASE wordpress_tests;"
      cp wp-tests-config-sample.php wp-tests-config.php
      sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
      sed -i "s/yourusernamehere/root/" wp-tests-config.php
      sed -i "s/yourpasswordhere//" wp-tests-config.php
      svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/wordpress-importer
  fi
- |
  if [[ "$WP_TRAVIS_OBJECT_CACHE" == "true" ]]; then
    curl https://raw.githubusercontent.com/tollmanz/wordpress-pecl-memcached-object-cache/584392b56dc4adbe52bd2c7b86f875e23a3e5f75/object-cache.php > src/wp-content/object-cache.php
    echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  fi
before_script:
- npm install -g npm
- npm install -g grunt-cli
- npm install
- npm prune
- mysql --version
- phpenv versions
- npm --version
- node --version
- composer install
- php make-action-cms.php
script: grunt $WP_TRAVISCI
